borg_version: 1.1.16
borg_sha256: fe1caaeee9354ead27379b8235a92eb1885d7948126d2edd49e60a2b85d4bcee

borg_agent: false
borg_agent_when: "00:00"
borg_agent_backup_paths: ["/"]
borg_agent_host_specific: ""
borg_agent_custom_opts: ""
borg_agent_delayed_start_max: 900
borg_agent_exclude: []
borg_agent_exclude_basic:
  - "/mnt/*"
  - "/media/*"
  - "/dev/*"
  - "/proc/*"
  - "/sys/*"
  - "/run/*"
  - "/tmp/*"
  - "**/lost+found"
  - "/usr/local/sbin/borg-agent"
  - "/var/lib/mysql/*"
  - "/var/lib/lxcfs"
  - "**/__pycache__"
  - "**/.cache*"
  - "**/.trash*"
  - "**/.thumb"
  - "**/.thumb*"
  - "**/tmp/*"
  - "/home/**/app/build/generated/*"
  - "/home/**/app/build/intermediates/*"
  - "/home/**/app/build/kotlin/*"
  - "/home/**/app/build/reports/*"
  - "/home/**/node_modules/"
  - "/home/**/venv/"
  - "/home/*/.kube/http-cache"
  - "/home/*/go/"
  - "/home/*/.npm/"
  - "/home/*/.rustup/"
  - "/home/*/.cargo/"
  - "/home/*/.pyenv/"
  - "/home/*/.android/"
  - "/home/*/.gradle/"
  - "/home/*/.bundle/"
  - "/home/*/.clion-*/"
  - "/home/*/.PyCharm*/"
  - "/home/*/.GoLand*/"
  - "/home/*/.arduino-*/"
  - "/home/*/.local/share/containers/"
  - "/home/*/.local/share/TelegramDesktop/"
  - "/var/tmp/*"
  - "/var/cache/*"
  - "/var/lib/apt/lists/*"
  - "/var/lib/docker/*"
  - "/var/lib/containerd/*"
  - "/var/lib/containers/*"
  - "/var/lib/kubelet/*"
  - "/var/lib/mysql/*"
  - "/var/lib/lxcfs/*"
  - "/var/lib/rancher/k3s/agent/*"
  - "/var/lib/rancher/k3s/data/*"
  - "/var/lib/rancher/k3s/server/*"
  - "/usr/lib/go*"

borg_agent_services: []
