- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Add Netsplit repository
      become: true
      apt_repository:
        filename: "netsplit"
        repo: "deb [trusted=yes] https://deb.netsplit.it/{{ ansible_distribution_release }} ./"

    - name: Add xrdp
      become: true
      apt:
        state: present
        name:
          - xrdp=0.9.12-1.1netsplit1
