- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Extract version from backup
      import_tasks: extract-version-from-backup.yml
      when: gitlab_bkfile is defined and gitlab_version is not defined

    # Install GitLab
    - name: Add gitlab repositories
      include_tasks: _apt-repo.yml
      loop:
        - name: gitlab
          key: https://packages.gitlab.com/gpg.key
          repo_line: "https://packages.gitlab.com/gitlab/gitlab-ee/debian/ {{ ansible_distribution_release }} main"

    - name: Install latest GitLab version
      become: true
      environment:
        EXTERNAL_URL: "{{ gitlab_external_url }}"
      apt:
        state: present
        pkg:
          - gitlab-ee
      when: gitlab_version is not defined

    - name: Install specific GitLab version
      become: true
      environment:
        EXTERNAL_URL: "{{ gitlab_external_url }}"
      apt:
        state: present
        pkg:
          - "gitlab-ee={{ gitlab_version }}.0"
      when: gitlab_version is defined

    - name: Restore from backup, if any
      import_tasks: restore-backup.yml
      when: gitlab_bkfile is defined and gitlab_bkcfg is defined
