- name: Remove manually installed exporter for node
  become: true
  file:
    path: /usr/local/sbin/node_exporter
    state: absent

- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Add Netsplit repository
      become: true
      apt_repository:
        filename: "netsplit"
        repo: "deb [trusted=yes] https://deb.netsplit.it/{{ ansible_distribution_release }} ./"

    - name: Add node exporter
      become: true
      apt:
        state: present
        name:
          - prometheus-node-exporter

# Remove old configuration from this playbook as the package already contains a systemd service
- name: Stop old systemd configuration
  become: true
  systemd:
    state: stopped
    name: node-exporter
    enabled: false

- name: Remove old systemd configurations
  become: true
  file:
    path: /etc/systemd/system/node-exporter.service
    state: absent
  notify:
    - "Reload systemd"
    - "Reset node-exporter failed"
