- name: Remove manually installed exporter for smartctl and old config
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/bin/exporter-smartctl
    - /etc/smartctl_exporter.yaml

- module_defaults:
    apt:
      cache_valid_time: 3600
  block:
    - name: Add Netsplit repository
      become: true
      apt_repository:
        filename: "netsplit"
        repo: "deb [trusted=yes] https://deb.netsplit.it/{{ ansible_distribution_release }} ./"

    - name: Add smartmontools for buster
      become: true
      apt:
        state: latest  # noqa package-latest
        name:
          - smartmontools
        default_release: buster-backports
      when: ansible_distribution_release == 'buster'

    - name: Add exporter for buster
      become: true
      apt:
        state: present
        name:
          - smartctl-exporter
      when: ansible_distribution_release == 'buster'

    - name: Add smartmontools and exporter
      become: true
      apt:
        state: present
        name:
          - smartmontools
          - smartctl-exporter
      when: ansible_distribution_release != 'buster'

- name: Create systemd service
  become: true
  template:
    src: exporter-smartctl.service.j2
    dest: "/etc/systemd/system/exporter-smartctl.service"
    owner: root
    group: root
    mode: '0600'
  notify: Restart smartctl exporter
