- name: Remove manually installed exporter for smartctl and old config
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/bin/exporter-smartctl
    - /etc/smartctl_exporter.yaml

- module_defaults:
    apt:
      cache_valid_time: 3600
  block:
    - name: Add Netsplit repository
      become: true
      copy:
        dest: "/etc/apt/sources.list.d/netsplit.list"
        content: |
          deb [trusted=yes] https://deb.netsplit.it/{{ ansible_distribution_release }} ./
          deb [trusted=yes] https://deb.netsplit.it/selfcontained ./

    - name: Add smartmontools and exporter
      become: true
      apt:
        update_cache: true
        state: present
        name:
          - smartmontools
          - smartctl-exporter

- name: Create systemd service
  become: true
  template:
    src: exporter-smartctl.service.j2
    dest: "/etc/systemd/system/exporter-smartctl.service"
    owner: root
    group: root
    mode: '0600'
  notify: Restart smartctl exporter
