- name: "Mikrotik: Remove old topic {{ item }}"
  community.network.routeros_command:
    commands:
      - /system/logging/remove [find action="logcollector" topics="{{ item }}"]
  register: command_result

- name: "Mikrotik: Add topic {{ item }}"
  community.network.routeros_command:
    commands:
      - /system/logging/add action="logcollector" topics="{{ item }}"
  register: command_result
  failed_when: >-
    "failure:" in command_result.stdout[0]
    or (command_result.stdout | length > 1 and "syntax error" in command_result.stdout[1])
    or "expected end of" in command_result.stdout[0]
