- name: Set rsyslog to log remotely
  become: true
  template:
    src: send-log.conf.j2
    dest: /etc/rsyslog.d/send-log.conf
    mode: '0600'
    owner: root
    group: root
  notify: "Restart rsyslog"
  when: >-
    (rsyslog_relp_host is defined and rsyslog_relp_host | length > 0)
    or (rsyslog_tcp_host is defined and rsyslog_tcp_host | length > 0)
    or (rsyslog_udp_host is defined and rsyslog_udp_host | length > 0)
