- name: Install gitlab-runner
  homebrew:
    name: gitlab-runner
    state: present

- name: Create .ssh directory
  file:
    path: ~/.ssh/
    state: directory
    mode: 0700
  when: runner_known_hosts is defined

- name: Copying .ssh
  copy:
    content: "{{ runner_known_hosts }}"
    dest: ~/.ssh/known_hosts
    mode: 0600
  when: runner_known_hosts is defined
