- name: Get local runners
  shell: >
    awk '$1=="[[runners]]" { RUNNER="" }; $1=="name" && RUNNER=="" { RUNNER=$3; print $3 };' {{ gitlab_runner_cfgpath }} | tr -d '"'
  register: localrunners
  changed_when: false
  check_mode: false

- name: Prepare list of configured runners
  set_fact:
    configured_runners: "{{ [inventory_hostname~'-'] | product(configured_runners_generic) | map('join') | list }}"
  vars:
    configured_runners_generic: "{{ runners | map(attribute='name') }}"

- name: "Register runner instance"
  command: >
    gitlab-runner register
    -r "{{ runner_reg_token }}"
    -n -u "{{ runner_reg_url }}"
    --executor "{{ runner_instance.executor }}"
    --locked="false"
    --paused="true"
    --tag-list "{{ runner_instance.tags | join(",") }}"
    --name "{{ inventory_hostname }}-{{ runner_instance.name }}"
    --output-limit {{ runner_instance.output_limit | default(32768) }}
    {% if runner_instance.executor == "docker" -%}
    --docker-image "{{ runner_instance.docker_default_image | default('debian:latest') }}"
    --docker-allowed-pull-policies "always,if-not-present"
    {% endif %}
    {% if runner_instance.executor == "virtualbox" %}
    --virtualbox-base-name "{{ runner_instance.vbox_vmname }}"
    --ssh-user "{{ runner_instance.ssh_user }}"
    --ssh-password "{{ runner_instance.ssh_pass }}"
    {% endif %}
    {% if runner_instance.executor == "custom" %}
    --builds-dir "{{ runner_instance.custom.builds_dir }}"
    --cache-dir "{{ runner_instance.custom.cache_dir }}"
    --custom-config-exec "{{ runner_instance.custom.config_exec | default("") }}"
    --custom-prepare-exec "{{ runner_instance.custom.prepare_exec | default("") }}"
    --custom-run-exec "{{ runner_instance.custom.run_exec | default("") }}"
    --custom-cleanup-exec "{{ runner_instance.custom.cleanup_exec | default("") }}"
    {% endif %}
  vars:
    runner_instance: "{{ runners | selectattr('name', 'in', item) | first }}"
  loop: "{{ configured_runners | difference(localrunners.stdout_lines) }}"
