# Secure SSH
ssh_hardening: true
ssh_root_key_access: true

# Firewall
fw_safe_mgmt4: []
fw_ssh_port: 22
fw_public_services: []
fw_whitelist_services: []
fw_rules: []
fw_iptables_filter: ""
fw_nft_input: ""

fw_iptables: false
fw_nftables: false

fw_blacklists: []
fw_whitelists: []

