# Secure SSH
ssh_hardening: true
ssh_root_key_access: true

# Firewall
fw_safe_mgmt4: []
fw_ssh_port: 22
fw_public_services: []
fw_whitelist_services: []
fw_rules: []
fw_iptables_filter: ""
fw_nft_input: ""

fw_iptables: false
fw_nftables: false

fw_blacklists: []
fw_whitelists: []
auditd_enabled: false
auditd_rules: ""
# rkhunter
rkhunter_enabled: false


# Secure machine
disable_core_dumps: false
secure_cron: false

molly_guard: true
banner_show_ssh: false
banner_text: |
  #############################################################################
  # UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED                          #
  #                                                                           #
  # You must have explicit, authorized permission to access or configure this #
  # device. Unauthorized attempts and actions to access or use this system    #
  # may result in civil and/or criminal penalties. All activities performed   #
  # on this device are logged and monitored.                                  #
  #                                                                           #
  # PRIVACY DISCLAIMER: Any personal data collected and processed on this     #
  # device is done in compliance with the General Data Protection Regulation  #
  # (GDPR). The legal basis for processing this data is the compliance with   #
  # legal obligation (Article 6, Paragraph 1.c).                              #
  #############################################################################

# Time sync
ntp_client: "timesyncd"
# if empty, timezone is not altered
ntp_timezone: ""
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

