# Secure SSH
ssh_hardening: true
ssh_root_key_access: true

# Firewall
# Enable either iptables, nftables or neither of those. When one is enabled,
# tools from the other are removed.
fw_iptables: false
fw_nftables: false
# These IPv4 and IPv6 are always allowed for SSH management, even before blacklists.
fw_safe_mgmt4: []
fw_safe_mgmt6: []
# SSH port for management (see above)
fw_ssh_port: 22
# These services are accessible by everyone, except IPs in blacklists.
fw_public_services: []
# These services are accessible only from IPs in whitelist (either lists or fixed IPs).
fw_whitelist_services: []
fw_whitelist_net4: []
fw_whitelist_net6: []
# These are generic rules.
fw_rules: []
# Here you can specify custom nft rules that are added in the "input" chain.
fw_nft_input: ""
# Blacklists names. Supported blacklists: TODO see in the script
fw_blacklists: []
# IP lists for the restricted services.
fw_whitelists: []




# fw_psad: false
# TODO: psad


auditd_enabled: false
auditd_rules: ""


# rkhunter
rkhunter_enabled: false


fail2ban_enabled: true



# Secure password - installs
# * cracklib-runtime
# * libpam-pwquality
# * libpam-tmpdir
secure_pam: false



# Secure machine
kernel_lockdown: false
disable_core_dumps: false
secure_logind: false
secure_cron: false
secure_sysctl: false

molly_guard: true
banner_show_ssh: false
banner_text: |
  #############################################################################
  # UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED                          #
  #                                                                           #
  # You must have explicit, authorized permission to access or configure this #
  # device. Unauthorized attempts and actions to access or use this system    #
  # may result in civil and/or criminal penalties. All activities performed   #
  # on this device are logged and monitored.                                  #
  #                                                                           #
  # PRIVACY DISCLAIMER: Any personal data collected and processed on this     #
  # device is done in compliance with the General Data Protection Regulation  #
  # (GDPR). The legal basis for processing this data is the compliance with   #
  # legal obligation (Article 6, Paragraph 1.c).                              #
  #############################################################################

# Time sync
ntp_client: "timesyncd"
# if empty, timezone is not altered
ntp_timezone: ""
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

# AIDE
aide_enabled: false
aide_custom_rules: |
  !/opt
  !/home
  !/root
  !/var/cache/
  !/var/lib/docker
  !/var/lib/containers
  !/var/lib/containerd
  !/var/lib/lxcfs/cgroup
  !/run
  !/tmp/tmux-0/default
  !/var/lib/dhcp
  !/var/log
