##### APT CONFIG: PROXY
- name: Remove previous APT local proxy config from Debian installer
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf
    state: absent
    regexp: "^Acquire::http::Proxy"

- name: Unset APT local proxy
  become: true
  file:
    path: /etc/apt/apt.conf.d/99proxy
    state: absent
  when: apt_proxy is not defined or apt_proxy == ''

- name: Set APT local proxy
  become: true
  template:
    src: 99proxy.j2
    dest: /etc/apt/apt.conf.d/99proxy
    mode: 0755
  when: apt_proxy is defined

##### SOURCES.LIST
- name: Set empty sources.list
  become: true
  copy:
    content: "# Source files are in /etc/apt/sources.list.d/"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  notify: ["Update APT"]

- name: Remove old dynamic files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/20-nas.list
    - /etc/apt/sources.list.d/50-debian.list
  notify: ["Update APT"]

- name: Set apt binary repositories
  become: true
  copy:
    content: |
      deb {{ apt_mirror }} {{ ansible_distribution_release }} main contrib non-free
      deb {{ apt_mirror }} {{ ansible_distribution_release }}-updates main contrib non-free
      deb {{ apt_security_mirror }} {{ ansible_distribution_release }}-security main contrib non-free
      deb {{ apt_mirror }} {{ ansible_distribution_release }}-backports main contrib non-free
    dest: /etc/apt/sources.list.d/20-debian-mirrors.list
    owner: root
    group: root
    mode: 0644
  notify: ["Update APT"]

- name: Set apt binary repositories fallback
  become: true
  copy:
    content: |
      deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free
      deb http://deb.debian.org/debian {{ ansible_distribution_release }}-updates main contrib non-free
      deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib non-free
      deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free
    dest: /etc/apt/sources.list.d/50-debian-fallback.list
    owner: root
    group: root
    mode: 0644
  when: apt_mirror != "http://deb.debian.org/debian" and apt_mirror_fallback
  notify: ["Update APT"]

- name: Remove apt binary repositories fallback
  become: true
  copy:
    dest: /etc/apt/sources.list.d/50-debian-fallback.list
    state: absent
  when: not apt_mirror_fallback
  notify: ["Update APT"]

- name: Set apt sources repositories
  become: true
  copy:
    content: |
      deb-src http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free
      deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-updates main contrib non-free
      deb-src http://security.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib non-free
      deb-src http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main contrib non-free
    dest: /etc/apt/sources.list.d/60-debian-sources.list
    owner: root
    group: root
    mode: 0644
  when: apt_sources
  notify: ["Update APT"]

##### OTHERS
- name: Executing all handlers
  meta: flush_handlers

- name: Remove unattended upgrades
  become: true
  apt:
    state: absent
    pkg:
      - unattended-upgrades
    purge: true

- name: Add Fast Track repository
  become: true
  apt:
    pkg:
      - fasttrack-archive-keyring

- name: Add Fast Track repository
  become: true
  apt_repository:
    filename: "fasttrack"
    repo: "deb http://fasttrack.debian.net/debian-fasttrack/ {{ ansible_distribution_release }}-fasttrack main contrib"
  when: debian_fasttrack

- name: Remove Fast Track repository
  become: true
  apt_repository:
    filename: "fasttrack"
    repo: "deb http://fasttrack.debian.net/debian-fasttrack/ {{ ansible_distribution_release }}-fasttrack main contrib"
    state: absent
  when: not debian_fasttrack

- name: Add Fast Track backports staging repository
  become: true
  apt_repository:
    filename: "fasttrack-backports-staging"
    repo: "deb http://fasttrack.debian.net/debian-fasttrack/ {{ ansible_distribution_release }}-backports-staging main contrib"
  when: debian_fasttrack

- name: Remove Fast Track backports staging repository
  become: true
  apt_repository:
    filename: "fasttrack-backports-staging"
    repo: "deb http://fasttrack.debian.net/debian-fasttrack/ {{ ansible_distribution_release }}-backports-staging main contrib"
    state: absent
  when: not debian_fasttrack

##### PVE

# - name: Add PVE enterprise repository
#   become: true
#   apt_repository:
#     filename: "pve-enterprise"
#     repo: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
#   when: apt_pve_enterprise

- name: Remove PVE enterprise repository
  become: true
  apt_repository:
    filename: "pve-enterprise"
    repo: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
    state: absent
  when: not apt_pve_enterprise

- name: Add PVE no-subscription repository
  become: true
  apt_repository:
    filename: "pve-no-subscription"
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
  when: apt_pve_nosubscription

- name: Remove PVE no-subscription repository
  become: true
  apt_repository:
    filename: "pve-no-subscription"
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    state: absent
  when: not apt_pve_nosubscription
