- name: Debian
  import_tasks: debian.yml
  when: (ansible_distribution_release == 'bullseye' or ansible_distribution_release == 'bookworm') and ansible_distribution == 'Debian'

- name: Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
