##### APT CONFIG: PHASED UPDATES
- name: Remove phased updates config
  become: true
  file:
    path: /etc/apt/apt.conf
    state: absent
  when: apt_phased_updates and apt_machine_id is not defined

- name: Configure phased updates config
  become: true
  template:
    src: 90phased-updates.j2
    dest: /etc/apt/apt.conf.d/90phased-updates
    mode: 0755
  when: not apt_phased_updates or apt_machine_id is defined

##### SOURCES.LIST
- name: Set empty sources.list
  become: true
  copy:
    content: "# Source files are in /etc/apt/sources.list.d/"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  notify: ["Update APT"]

- name: Set apt binary repositories
  become: true
  copy:
    content: |
      deb {{ apt_ubuntu_mirror }} {{ ansible_distribution_release }} main restricted universe multiverse
      deb {{ apt_ubuntu_mirror }} {{ ansible_distribution_release }}-updates main restricted universe multiverse
      deb {{ apt_ubuntu_security_mirror }} {{ ansible_distribution_release }}-security main restricted universe multiverse
      deb {{ apt_ubuntu_mirror }} {{ ansible_distribution_release }}-backports main restricted universe multiverse
    dest: /etc/apt/sources.list.d/20-ubuntu-mirrors.list
    owner: root
    group: root
    mode: 0644
  notify: ["Update APT"]

- name: Set apt binary repositories fallback
  become: true
  copy:
    content: |
      deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse
    dest: /etc/apt/sources.list.d/50-ubuntu-fallback.list
    owner: root
    group: root
    mode: 0644
  when: apt_ubuntu_mirror != "http://archive.ubuntu.com/ubuntu/" and apt_mirror_fallback
  notify: ["Update APT"]

- name: Remove apt binary repositories fallback
  become: true
  copy:
    dest: /etc/apt/sources.list.d/50-ubuntu-fallback.list
    state: absent
  when: not apt_mirror_fallback
  notify: ["Update APT"]

- name: Set apt sources repositories
  become: true
  copy:
    content: |
      deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse
      deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse
      deb-src http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse
      deb-src http://archive.ubuntu.com/ubuntu// {{ ansible_distribution_release }}-backports main restricted universe multiverse
    dest: /etc/apt/sources.list.d/60-ubuntu-sources.list
    owner: root
    group: root
    mode: 0644
  when: apt_sources
  notify: ["Update APT"]
