- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Add codium repositories
      include_tasks: _apt-repo.yml
      loop:
        - name: vscodium
          key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
          repo_line: "{{ codium_mirror }}/debs/ vscodium main"

    - name: Install Codium
      become: true
      apt:
        state: present
        pkg:
          - codium
