- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Install dependencies
      become: true
      apt:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present

    - name: Add PostgreSQL GPG key
      become: true
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repository
      become: true
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ hostvars[inventory_hostname]['ansible_distribution_release'] }}-pgdg main"
        state: present

    - name: Add Timescale GPG key
      become: true
      apt_key:
        url: https://packagecloud.io/timescale/timescaledb/gpgkey
        state: present

    - name: Add TimescaleDB repository
      become: true
      apt_repository:
        repo: "deb https://packagecloud.io/timescale/timescaledb/debian/ {{ hostvars[inventory_hostname]['ansible_distribution_release'] }} main"
        state: present

    - name: Install TimescaleDB
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - timescaledb-tools
        - timescaledb-2-postgresql-14
      notify: "Restart TimescaleDB"

    - name: TimescaleDB auto-tune parameters
      become: true
      command: timescaledb-tune -yes
      changed_when: false

    - name: Disable TimescaleDB telemetry
      become: true
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        line: timescaledb.telemetry_level=off
        state: present
      notify: "Restart TimescaleDB"

    - name: Flush handlers
      meta: flush_handlers

    - name: Restore backup
      import_tasks: restore.yml
      when: timescale_db_name is defined and timescale_db_file is defined
