- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Add PostgreSQL and TimescaleDB repositories
      include_tasks: _apt-repo.yml
      loop:
        - name: pgsql
          key: https://www.postgresql.org/media/keys/ACCC4CF8.asc
          repo_line: "http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        - name: timescale
          key: https://packagecloud.io/timescale/timescaledb/gpgkey
          repo_line: "https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release }} main"

    - name: Install TimescaleDB
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - timescaledb-tools
        - timescaledb-2-postgresql-14
      notify: "Restart TimescaleDB"

    - name: TimescaleDB auto-tune parameters
      become: true
      command: timescaledb-tune -yes
      changed_when: false

    - name: Disable TimescaleDB telemetry
      become: true
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        line: timescaledb.telemetry_level=off
        state: present
      notify: "Restart TimescaleDB"

    - name: Flush handlers
      meta: flush_handlers

    - name: Restore backup
      import_tasks: restore.yml
      when: timescale_db_name is defined and timescale_db_file is defined
