- name: Update GRUB
  become: true
  command: update-grub2

- name: Reload sysctl
  become: true
  command: sysctl -p

- name: Restart SSH server
  become: true
  systemd:
    name: sshd
    state: restarted

- name: Reload iptables rules
  become: true
  systemd:
    name: netfilter-persistent
    state: restarted

- name: Reload nftables rules
  become: true
  systemd:
    name: nftables
    state: restarted

- name: Reload black/white lists
  become: true
  command: /usr/local/sbin/fw-lists-update
  when: fw_blacklists or fw_whitelists

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply AIDE database
  become: true
  command: cp -p /var/lib/aide/aide.db.new /var/lib/aide/aide.db

- name: Restart chronyd
  become: true
  systemd:
    name: chronyd
    state: restarted

- name: Reload chronyd sources
  become: true
  command: chronyc reload sources

- name: Restart systemd-timesyncd
  become: true
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: Update rkhunter db
  become: true
  command: rkhunter --propupd
  when: rkhunter_enabled

- name: Restart auditd
  become: true
  systemd:
    name: auditd
    state: restarted

- name: Restart fail2ban
  become: true
  systemd:
    name: fail2ban
    state: restarted
