- name: Check supported Debian versions
  become: true
  fail:
    msg: "This playbook supports only Debian 11 and 12"
  when: ansible_distribution_release != 'bullseye' and ansible_distribution_release != 'bookworm'

- name: Install base tools (Intel-compatible only)
  become: true
  apt:
    pkg:
      - acpi
  when: build_tools and ansible_machine == 'x86_64'

- name: Install base tools
  become: true
  apt:
    pkg:
      - minicom
      - iperf
      - iperf3
      - ethtool
      - openvpn
      - p7zip
      - smartmontools
      - pass
      - vbindiff
      - sipcalc
      - bsdutils
      - bsdmainutils
      - binwalk
      - socat
      - aria2
      - jq
      - redis-tools
      - sqlite3
      - tcpdump
      - build-essential
      - git
      - curl
      - default-libmysqlclient-dev
      - default-mysql-client
      - gawk
      - make
      - markdown
      - tmux
      - mtr-tiny
      - python3
      - python3-pexpect  # for some playbooks
      - python3-pip
      - python3-all-dev
      - python3-virtualenv
      - rsync
      - vim
      - wget
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - postgresql-client
      - redis-tools
      - unzip
      - gradle
      - wireguard
    update_cache: true
    cache_valid_time: 1
  when: build_tools

- name: Install X11 base tools
  become: true
  apt:
    state: present
    name:
      - xterm
      - xinit
      - xserver-xorg
      - tigervnc-viewer
      - chromium
      - firefox-esr
      - task-xfce-desktop
      - lightdm
      - cups
      - zenity
      - dbus-x11
      - xscreensaver
  when: x11

- name: Remove X11 base tools
  become: true
  apt:
    state: absent
    name:
      - xterm
      - xinit
      - xserver-xorg
      - tigervnc-viewer
      - chromium
      - firefox-esr
      - task-xfce-desktop
      - lightdm
      - cups
      - zenity
      - dbus-x11
      - xscreensaver
  when: not x11
