# Set brew path for M1 chips
- name: Set brew path for M1
  set_fact:
    brewbin: /opt/homebrew/bin/
  when: ansible_architecture == 'arm64'

- name: Set brew path globally for M1
  become: true
  copy:
    content: |
      /opt/homebrew/bin/
    dest: /etc/paths.d/100homebrew
    mode: 0644
  when: ansible_architecture == 'arm64'

- name: Set brew path for amd64
  set_fact:
    brewbin: /usr/local/bin/
  when: ansible_architecture == 'x86_64'

- name: Installing base tools
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - coreutils
    - carthage
    - jq
    - fastlane
    - cocoapods

# https://stackoverflow.com/questions/60481623/errors-when-installing-cocoapods-with-gem
- name: Switch to macOS Command line tools
  become: true
  command: xcode-select --switch /Library/Developer/CommandLineTools
  changed_when: false

- name: Enable Rosetta 2
  become: true
  command: softwareupdate --install-rosetta --agree-to-license
  when: ansible_architecture == 'arm64'
