- name: Installing Homebrew
  import_role:
    name: geerlingguy.mac.homebrew

- name: Check if home directory exists
  become: true
  stat:
    path: "/Users/{{ ansible_user }}"
  register: homedirpath

- name: Create home directory
  become: true
  command: createhomedir -c -u {{ ansible_user }}
  when: not homedirpath.stat.exists

- name: Fix SNTP sync
  become: true
  copy:
    content: ""
    dest: /var/db/ntp-kod
    mode: '0644'
    owner: root
    group: wheel
  notify: "Sync NTP"

- name: Disable setup assistant
  become: true
  copy: # TODO: this file changes between macOS versions
    src: com.apple.SetupAssistant.plist
    dest: "/Users/{{ ansible_user }}/Library/Preferences/com.apple.SetupAssistant.plist"
    mode: '0600'

- name: Disable auto updates
  become: true
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: bool
    value: false
  loop:
    - { domain: com.apple.SoftwareUpdate, key: AllowPreReleaseInstallation }
    - { domain: com.apple.SoftwareUpdate, key: AutomaticallyInstallAppUpdates }
    - { domain: com.apple.SoftwareUpdate, key: AutomaticallyInstallMacOSUpdates }
    - { domain: com.apple.SoftwareUpdate, key: AutomaticCheckEnabled }
    - { domain: com.apple.SoftwareUpdate, key: AutomaticDownload }
    - { domain: com.apple.SoftwareUpdate, key: ConfigDataInstall }
    - { domain: com.apple.SoftwareUpdate, key: CriticalUpdateInstall }
    - { domain: com.apple.commerce, key: AutoUpdate }
    - { domain: com.apple.commerce, key: AutoUpdateRestartRequired }
  when: macos_disable_updates

- name: Read dev tool security status
  command: DevToolsSecurity -status
  register: devtoolseccmd
  changed_when: false

- name: Enable Developer Mode
  become: true
  command: DevToolsSecurity -enable
  when: '"Developer mode is currently enabled." not in devtoolseccmd.stdout'

- name: Add info panel to clock in login window
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: AdminHostInfo
    type: string
    value: HostName

- name: Add keyboard input in login screen
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: showInputMenu
    type: string
    value: true

- name: Show username/password prompt instead of user list
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: SHOWFULLNAME
    type: bool
    value: true

- name: Show username/password prompt instead of user list 2
  become: true
  community.general.osx_defaults:
    domain: com.apple.loginwindow
    key: AllowList
    type: string
    value: "*"

- name: Disable save application state on logout
  community.general.osx_defaults:
    domain: com.apple.loginwindow
    key: TALLogoutSavesState
    type: bool
    value: false

- name: Set GMT for UTC time zones in defaults
  set_fact:
    time_zone: "GMT"
  when: time_zone == "UTC"

- name: Get current time zone
  become: true
  command: systemsetup -gettimezone
  register: currenttz

- name: Set time zone
  become: true
  command: "systemsetup -settimezone {{ time_zone }}"
  when: 'currenttz.stdout[0] != "Time Zone: " + time_zone'

- name: Executing all handlers
  meta: flush_handlers
