- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Check role compatibility
      fail:
        msg: This role is compatible only with Debian 10 buster
      when: ansible_distribution_release != 'buster'

    - name: Add NVIDIA repositories
      include_tasks: _apt-repo.yml
      loop:
        - name: libnvidia-container
          key: https://nvidia.github.io/nvidia-docker/gpgkey
          repo_line: "https://nvidia.github.io/libnvidia-container/stable/debian10/$(ARCH) /"
        - name: nvidia-container-runtime
          key: https://nvidia.github.io/nvidia-docker/gpgkey
          repo_line: "https://nvidia.github.io/nvidia-container-runtime/stable/debian10/$(ARCH) /"
        - name: nvidia-docker
          key: https://nvidia.github.io/nvidia-docker/gpgkey
          repo_line: "https://nvidia.github.io/nvidia-docker/debian10/$(ARCH) /"

    - name: Install NVIDIA packages
      become: true
      apt:
        pkg:
          - firmware-linux
          - firmware-misc-nonfree
          - linux-headers-amd64
          - nvidia-driver
          - nvidia-smi
          - nvidia-cuda-dev
          - nvidia-cuda-toolkit
          - nvidia-container-toolkit
        state: present
      notify: "Reboot"
