- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Check role compatibility
      fail:
        msg: This role is compatible only with Debian 10 buster
      when: ansible_distribution_release != 'buster'

    - name: Adding NVIDIA repo key
      become: true
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present

    - name: Adding NVIDIA repositories
      become: true
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "deb https://nvidia.github.io/libnvidia-container/stable/debian10/$(ARCH) /"
        - "deb https://nvidia.github.io/nvidia-container-runtime/stable/debian10/$(ARCH) /"
        - "deb https://nvidia.github.io/nvidia-docker/debian10/$(ARCH) /"

    - name: Install NVIDIA packages
      become: true
      apt:
        pkg:
          - firmware-linux
          - firmware-misc-nonfree
          - linux-headers-amd64
          - nvidia-driver
          - nvidia-smi
          - nvidia-cuda-dev
          - nvidia-cuda-toolkit
          - nvidia-container-toolkit
        state: present
      notify: "Reboot"
