- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Fix udev rules for Android
      become: true
      lineinfile:
        state: present
        dest: /etc/udev/rules.d/51-android.rules
        create: true
        line: SUBSYSTEM=="usb", ATTR{idVendor}=="22b8", ATTR{idProduct}=="2e81", MODE="0666", GROUP="plugdev"
        mode: 0644
      notify: "Reload udev rules"

    - name: Check if VMX/SVM virtualization extensions are available
      command: egrep -q '(vmx|svm)' /proc/cpuinfo
      register: vmxavailable
      ignore_errors: true
      changed_when: false
      when: ansible_virtualization_role != 'guest'

    - name: Install KVM if possible
      become: true
      apt:
        state: present
        pkg:
          - qemu-kvm
          - libvirt-clients
          - libvirt-daemon-system
          - virtinst
      when: ansible_virtualization_role != 'guest' and vmxavailable is success and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

    - name: Installing OpenJDK
      become: true
      apt:
        state: present
        pkg:
          - openjdk-11-jdk
