# Set brew path for M1 chips
- name: Get brew path for M1
  set_fact:
    brewbin: /opt/homebrew/bin/
  when: ansible_architecture == 'arm64'

- name: Get brew path for amd64
  set_fact:
    brewbin: /usr/local/bin/
  when: ansible_architecture == 'x86_64'

- name: Install gradle
  homebrew:
    name: gradle
    state: present

- name: Installing Android SDK manager
  homebrew_cask:
    name: "android-commandlinetools"
    state: present

- name: Accepting all licenses
  expect:
    command: "{{ brewbin }}/sdkmanager --licenses"
    responses:
      'y/N': 'y'

- name: Installing Android SDK base packages
  expect:
    command: "{{ brewbin }}/sdkmanager \"{{ item }}\""
    responses:
      'y/N': 'y'
    timeout: 120
  loop:
    - "cmdline-tools;latest"
    - "tools"
    - "platform-tools"
    - "build-tools;{{ android_sdk_build_tools }}"

- name: Installing Android SDK platforms and packages
  expect:
    command: "{{ brewbin }}/sdkmanager \"{{ item }}\""
    responses:
      'y/N': 'y'
    timeout: 120
  loop: '{{ android_sdk_packages }}'
