- name: Installing pexpect (playbook requirement)
  pip:
    state: latest
    name: pexpect
    extra_args: --user

# Workaround for SUDO_ASKPASS
# Create Ansible bin dir in home dir
- name: create ansible bin dir in home
  file: path=~/.ansible/bin/ state=directory
  changed_when: false

# Copy temporary sudo ask pass script
- name: copy sudo ask pass script
  template:
    src: sudo_askpass.tmp.sh.j2
    dest: ~/.ansible/bin/sudo_askpass.tmp.sh
    mode: 0700
    backup: no
  changed_when: false

- name: Installing Temurin Java 11
  homebrew_cask:
    name: homebrew/cask-versions/temurin11
    state: present
  environment:
    SUDO_ASKPASS: "{{ ansible_user_dir }}/.ansible/bin/sudo_askpass.tmp.sh"

# Delete temporary sudo ask pass script
- name: delete sudo ask pass script
  file: path=~/.ansible/bin/sudo_askpass.tmp.sh state=absent
  changed_when: false
