- name: Remove old playbook versions of restic
  file:
    path: /usr/local/bin/restic
    state: absent
  when: ansible_os_family == 'Debian'

- name: Add Netsplit repository
  become: true
  copy:
    dest: "/etc/apt/sources.list.d/netsplit.list"
    content: |
      deb [trusted=yes] https://deb.netsplit.it/{{ ansible_distribution_release }} ./
      deb [trusted=yes] https://deb.netsplit.it/selfcontained ./
  when: ansible_os_family == 'Debian'

- name: Install restic package
  become: true
  apt:
    pkg:
      - restic
    state: present
    default_release: "o=Netsplit,n={{ ansible_distribution_release }},c="
  when: ansible_os_family == 'Debian' and not restic_stdin_experiment

- name: Install restic package (experiment)
  become: true
  apt:
    pkg:
      - restic-stdin-from-command
    state: present
    default_release: "o=Netsplit,n={{ ansible_distribution_release }},c="
  when: ansible_os_family == 'Debian' and restic_stdin_experiment

# Restic in dnf is too old
# - name: Install restic package
#   become: true
#   ansible.builtin.dnf:
#     pkg: restic
#     state: present
#   when: ansible_os_family == 'RedHat'

- name: Install binary from GitHub
  include_tasks: restic-dl.yml
  when: ansible_os_family != 'Debian' # and ansible_os_family != 'RedHat'
