### Non Debian-system, use the binary provided by github
- name: Check if restic-rest-server is present
  stat:
    checksum_algorithm: sha256
    get_checksum: true
    path: /usr/local/bin/rest-server
  register: restic_rest_executable

- name: Set restic download file name
  set_fact:
    rest_server_dl_fname: "rest-server_{{ rest_server_version }}_{{ ansible_system | lower }}_{{ architectures[ansible_architecture] }}.tar.gz"
  when: not restic_rest_executable.stat.exists or restic_rest_executable.stat.checksum != rest_server_sha256[ansible_system][ansible_architecture]

- name: Download restic-rest-server
  get_url:
    url: "https://github.com/restic/rest-server/releases/download/v{{ rest_server_version }}/{{ rest_server_dl_fname }}"
    dest: /tmp/restic-rest-server.tar.gz
    checksum: sha256:https://github.com/restic/rest-server/releases/download/v{{ rest_server_version }}/SHA256SUMS
  when: not restic_rest_executable.stat.exists or restic_rest_executable.stat.checksum != rest_server_sha256[ansible_system][ansible_architecture]
  register: restic_rest_download

- name: Decompress restic-rest-server
  ansible.builtin.unarchive:
    src: /tmp/restic-rest-server.tar.gz
    remote_src: true
    dest: /tmp/
    extra_opts: ["--strip-components=1"]
  when: restic_rest_download is not skipped

- name: Install restic-rest-server
  become: true
  copy:
    remote_src: true
    src: /tmp/rest-server
    dest: /usr/local/bin/rest-server
    owner: root
    group: root
    mode: '0755'
  when: restic_rest_download is not skipped
