- name: Install rclone
  become: true
  apt:
    pkg:
      - rclone
    state: present

# TODO: copy file with token

- name: Add cronjob for synchronizing cameras
  become: true
  cron:
    name: "sync motion files"
    minute: "*"
    hour: "*"
    job: "rclone sync /var/lib/motion {{ motion_rclone_remote }}:webcam/{{ camera.tag }}"
    user: root
  loop: "{{ motion_cameras }}"
  loop_control:
    loop_var: camera
    label: "{{ camera.tag }}"
  when: "'rclone' in camera and camera.rclone"
