- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Add Kubernetes tools repositories
      include_tasks: _apt-repo.yml
      loop:
        - name: kubernetes-tools
          key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          repo_line: "https://apt.kubernetes.io/ kubernetes-xenial main"

    - name: Install kubectl
      become: true
      apt:
        state: present
        pkg:
          - kubectl
