- name: Refresh CA certificates local store
  become: true
  command: update-ca-certificates

- name: Reload docker
  become: true
  systemd:
    state: restarted
    daemon_reload: true
    name: docker
    enabled: true

- name: Update APT
  become: true
  command: apt-get update
