- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Installing OpenJDK
      become: true
      apt:
        state: present
        pkg:
          - openjdk-11-jdk
      when: "'jdk11' in jdk_versions"

    - name: Installing OpenJDK
      become: true
      apt:
        state: present
        pkg:
          - openjdk-17-jdk
      when: "'jdk17' in jdk_versions"

    - name: Add AdoptOpenJDK repositories
      include_tasks: _apt-repo.yml
      loop:
        - name: adoptopenjdk
          key: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
          repo_line: "https://adoptopenjdk.jfrog.io/adoptopenjdk/deb {{ ansible_distribution_release }} main"
      when: "'jdk8' in jdk_versions"

    - name: Installing AdoptOpenJDK 8
      become: true
      apt:
        state: present
        pkg:
          - adoptopenjdk-8-hotspot
      when: "'jdk8' in jdk_versions"
