disable_mitigations: false
x11: false
install_script: false

build_tools: true

macos_disable_updates: false
macos_xcode_url: ""
macos_xcode_version: ""

install_xcode: false

disable_iommu_passthrough: false

remote_access: false

time_zone: "UTC"
