- name: Executing all handlers
  meta: flush_handlers

- name: Debian
  import_tasks: debian.yml
  when: (ansible_distribution_release == 'bullseye' or ansible_distribution_release == 'bookworm') and ansible_distribution == 'Debian'
