- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Remove locally installed borg
      become: true
      file:
        path: /usr/local/bin/borg
        state: absent

    - name: Install packaged Borg Backup software from backports
      become: true
      apt:
        pkg:
          - borgbackup
        state: present
        default_release: bullseye-backports
      when: ansible_distribution_release == 'bullseye'

    - name: Install packaged Borg Backup software
      become: true
      apt:
        pkg:
          - borgbackup
        state: present
      when: ansible_distribution_release == 'bookworm'
