- name: Install coturn
  become: true
  apt:
    name:
      - coturn
  when: prosody_turn_enabled

- name: Generate coturn configuration
  become: true
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
    mode: '0640'
    owner: root
    group: turnserver
  notify: "Restart coTURN"
  when: prosody_turn_enabled
