## WARNING: untested
## TODO: support other OSes

- name: Check if kernel lockdown mode has been already activated
  lineinfile:
    dest: /etc/default/grub
    line: "lockdown=confidentiality"
  check_mode: yes
  register: kernel_lockdown_line
  changed_when: false

- name: Enable kernel lockdown
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 lockdown=confidentiality"'
    backrefs: yes
  when: kernel_lockdown_line.changed
  notify: ["Update GRUB"]

# TODO: kernel.modules_disabled, kernel.kexec_load_disabled
