# TODO: add a note in the README about this breaking tmux, screen, nohup and others
- name: Set secure default for logind
  become: true
  copy:
    path: /etc/systemd/logind.conf
    content: |
      [Login]
      KillUserProcesses=1
      KillExcludeUsers=root
      IdleAction=lock
      IdleActionSec=15min
      RemoveIPC=yes
    mode: 0640
    owner: root
    group: root
  notify: ["Reload systemd"]
