- name: check fw_iptables and fw_nftables
  fail:
    msg: Can't have both fw_iptables and fw_nftables at the same time
  when: fw_iptables and fw_nftables

- name: Harden SSH
  include_tasks: ssh.yaml
  when: ssh_hardening

- name: firewall blacklists/whitelists
  include_tasks: fw_lists.yaml
  when: (fw_blacklists | length) > 0 or (fw_whitelists | length) > 0

- name: iptables firewall
  include_tasks: iptables.yaml
  when: fw_iptables

- name: nftables firewall
  include_tasks: nftables.yaml
  when: fw_nftables

- name: APT
  include_tasks: apt.yaml
  when: ansible_os_family == 'Debian'

- name: banner
  include_tasks: banner.yaml


- name: rkhunter
  include_tasks: rkhunter.yaml
  when: rkhunter_enabled
- name: Ubuntu-specific
  include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'

- name: cleanup
  include_tasks: cleanup.yaml
