- name: Create /etc/sudoers.d if it does not exist
  become: true
  file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Pass SSH_CONNECTION env in sudo env for molly-guard
  become: true
  copy:
    content: |
      Defaults env_keep += SSH_CONNECTION
    dest: /etc/sudoers.d/50-molly-guard
    owner: root
    group: root
    mode: '0600'

- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Install molly-guard (apt)
      become: true
      apt:
        name: molly-guard
        state: present
      when: ansible_os_family == 'Debian'

    # NO PACKAGE, REPLACE WITH A SIMILAR ONE?
    # - name: Install molly-guard (dnf)
    #   become: true
    #   dnf:
    #     name: molly-guard
    #     state: present
    #   when: ansible_os_family == 'RedHat'
