- name: Install rkhunter package
  become: true
  apt:
    name: rkhunter
    state: present

- name: Configure rkhunter to run daily
  become: true
  lineinfile:
    dest: /etc/default/rkhunter
    regexp: '^CRON_DAILY_RUN='
    line: 'CRON_DAILY_RUN="yes"'
  notify: "Restart rkhunter"

- name: Configure rkhunter to run daily
  become: true
  lineinfile:
    dest: /etc/default/rkhunter
    regexp: '^APT_AUTOGEN='
    line: 'APT_AUTOGEN="yes"'
  notify: "Restart rkhunter"
