- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Install snmpd
      become: true
      ansible.builtin.dnf:
        pkg: net-snmp
        state: present

    - name: Copy snmpd config
      become: true
      template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
      notify: "Restart snmpd"

    - name: Enable systemd
      become: true
      ansible.builtin.systemd:
        name: snmpd
        enabled: true
        state: started
        daemon_reload: true

    - name: Enable snmpd
      become: true
      command: chkconfig snmpd on

    - name: Copy snmp-get-dnf-updates script
      become: true
      copy:
        src: snmp-get-dnf-updates.sh
        dest: /usr/local/sbin/snmp-get-dnf-updates.sh
        owner: root
        group: root
        mode: 0755
