- name: Restart smartctl exporter
  become: true
  systemd:
    state: restarted
    name: exporter-smartctl
    daemon_reload: true
    enabled: true

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: true

- name: Reset node-exporter failed
  become: true
  command: systemctl reset-failed node-exporter
  ignore_errors: true
