- module_defaults:
    apt:
      cache_valid_time: 86400
  block:
    - name: Install Wireguard on Debian
      import_tasks: linux-cfg.yml
      when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") and ansible_network_os is not defined

    - name: Install Wireguard on Mikrotik
      import_tasks: mikrotik.yml
      when: ansible_network_os is defined and ansible_network_os == 'community.network.routeros'


- name: Dump roaming configurations
  include_tasks: "roaming-cfg.yml"
  loop: "{{ groups[wireguard_cfg_dump_group] }}"
  loop_control:
    loop_var: rhost
    label: "Host"
  when: wireguard_cfg_dump
