- name: Set peer
  include_tasks: "mikrotik-wg-peers-item.yml"
  loop: "{{ peer['value']['wireguard'] | selectattr('name', '==', wg.name) }}"
  loop_control:
    loop_var: item
    label: "{{ item.endpoint_host }}"
